### PR TITLE
await_all 2

### LINKED ISSUE #171: BUG: await_all fails
`await_all` is failing this example:

```
ids <- c(23820523, 23820523)
runs <- c(130390319, 130390319)
await_all(scripts_get_r_runs, .x = ids, .y = runs)
```

I think this has to do with passing args to `call_once` and `safe_call_once`. This will require a little refactoring of the existing `call_once` and maybe the tests as well.

@Zephyraith would you be up to taking a look?

### PR DESCRIPTION
**Pull request by patr1ckm**
Here's a fix for `await_all`. It is now vectorized over two arguments, and still works if only given `.x`. `call_once` was refactored to remove an unnecessary `.id` parameter.

```
ids <- c(23820523, 23820523)
runs <- c(130390319, 130390319)
await_all(scripts_get_r_runs, .x = ids, .y = runs)

# produces timeout error
await_all(scripts_get_r_runs, .x = ids, .y = runs, .success_states = 'asdf', .timeout = 1)

# nice logging
await_all(scripts_get_r_runs, .x = ids, .y = runs, .success_states = 'asdf', .verbose = TRUE, .timeout=2)
```
Fixes #171 . @Zephyraith thanks for the 30% WIP to get this started!

### CODE REVIEW

File: tests/testthat/test_await.R [hunk 1]
```diff
@@ -243,17 +243,18 @@ test_that("await_all calls f until completion - multivariate", {
...
+               list(list(job_id = 1, run_id = 3),
+                    list(job_id = 2, run_id = 4)))
 })
 
 test_that("await_all catches arbitrary status and keys - multivariate", {
   f <- function(x, y) list(party_status = "going home", value = x)
   x <- await_all(f, .x = 1:2, .y = 3:4, .status_key = "party_status",
                  .success_states = "going home", .verbose = TRUE)
   expect_equal(sapply(x, get_status), rep("going home", 2))
-  expect_equal(sapply(x, function(x) x$value), cbind(c(1, 3), c(2, 4)))
```
Comment (patr1ckm) [inline tests/testthat/test_await.R]: I'm not sure why this was ever the intended behavior, since `f` only returns `x` in the value slot.

File: tests/testthat/test_await.R [hunk 2]
```diff
@@ -127,20 +127,20 @@ test_that("verbose produces correct messages", {
...
 
 test_that("if called, get_status(r$response) returns status", {
   f <- function(id) return(list(state = "succeeded"))
-  expect_equal(get_status(call_once(f, .id = 1, fname = "f")$response), "succeeded")
+  expect_equal(get_status(call_once(f, 1, fname = "f")$response), "succeeded")
 })
 
 test_that("call_once captures completed_states and status_keys", {
   f <- function(id) return(list(party_status = "at the party"))
-  expect_true(call_once(f, .id = 1, .success_states = "at the party",
```
Comment (keithing) [inline tests/testthat/test_await.R]: why do these changes need to be made?

Comment (patr1ckm) [reply tests/testthat/test_await.R]: I had written `call_once` with an `.id` argument previously to facilitate vectorization previously in `await_all`. It's not needed. The change in the test removes the `.id` named parameter in `call_once`.
